const { GoogleGenAI } = require("@google/genai");
const {z} = require("zod")
const zodJsonSchema = require("zod-to-json-schema").default
const puppeteer = require("puppeteer")

const ai = new GoogleGenAI({
    apiKey: process.env.GOOGLE_GENAI_API_KEY,
});

async function generateInterviewReport({ resume, selfDescription, jobDescription }){
    try {
        if (!resume || !selfDescription || !jobDescription) {
            throw new Error('Missing required parameters: resume, selfDescription, or jobDescription');
        }

        const prompt = 
            `You are an expert interview coach. You have to generate a detailed interview report for a candidate based on the following information:
            Resume: ${resume}
            Self Description: ${selfDescription}
            Job Description: ${jobDescription}
            
            Respond with ONLY a valid JSON object (no markdown, no extra text) with the following structure:
            {
              "title": string, //The title of the job for which the interview report is getting generated.
              "matchScore": number (0-100),
              "technicalQuestions": [{"question": string, "intention": string, "answer": string}],
              "behavioralQuestions": [{"question": string, "intention": string, "answer": string}],
              "skillGaps": [{"skill": string, "severity": "low"|"medium"|"high"}],
              "preparationPlan": [{"day": number, "focus": string, "tasks": string[]}]
            }`;

        const response = await ai.models.generateContent({
            model: "gemini-3.6-flash",
            contents: prompt,
        });

        if (!response || !response.text) {
            throw new Error('Invalid response from AI model');
        }

        const reportData = JSON.parse(response.text);
        console.log('Interview Report Generated:', reportData);
        return reportData;
    } catch (error) {
        console.error('Error generating interview report:', error.message);
        throw error;
    }
}

async function generatePdfFromHtml(htmlContent){
    const browser = await puppeteer.launch();
    try {
        const page = await browser.newPage();
        await page.setContent(htmlContent, {waitUntil:"networkidle0"})
        return await page.pdf({format:"A4",margin:{
            top:"20mm",
            bottom:"20mm",
            left:"15mm",
            right:"15mm",
        }})
    } finally {
        await browser.close()
    }
}

async function generateResumePdfFromHTML({resume, selfDescription, jobDescription}){
    if (!resume || !selfDescription || !jobDescription) {
        throw new Error('Missing required parameters: resume, selfDescription, or jobDescription');
    }

    const resumePdfSchema = z.object({
        html: z.string().describe('HTML content of the resume')
    });

    const prompt = `Generate resume HTML for a candidate using the following details:
                    Resume: ${resume}
                    Self Description: ${selfDescription}
                    Job Description: ${jobDescription}
                    Return only a JSON object with one field, "html". The html field must contain a complete, printable resume document.
                    The content of the resume should be not sound like its generated by AI and should be as close as possible to a real human-written resume
                    The resume should be tailored for the given job description and should highlight the candidate's strength and relevant experience. The HTML content should be well formatted and structured, making it easy to read and visual appealing
                    You can highlight the content using some colors or different font styles but overall design should be simple and professional
                    The content should be ATS friendly, i.e. it should be easily parsable by ATS systems without losing important information.
                    The Resume should not be so lenghty, it should be ideally be 1 pags long when converted to PDF. Focus on quality rather than quantity and make sure to include all the relevant information that can increase the candidates chance of getting an interview call for the given job description. `;

    try {
        const response = await ai.models.generateContent({
            model: "gemini-3.6-flash",
            contents: prompt,
            config: {
                responseMimeType: "application/json",
                responseSchema: zodJsonSchema(resumePdfSchema)
            }
        });

        if (!response?.text) {
            throw new Error('Invalid response from AI model');
        }

        const {html} = resumePdfSchema.parse(JSON.parse(response.text));
        return generatePdfFromHtml(html);
    } catch (error) {
        console.error('Error generating resume HTML:', error.message);
        throw error;
    }
}

module.exports = {generateInterviewReport, generateResumePdfFromHTML}; 